异步编程体验
xiaoqiang0723/test pull request #11
Opened 2018-05-25 09:29 UTC by xiaoqiang0723

2018-05-25 09:45 UTC, vincent-ng requested changes

2018-05-25 09:45 UTC, vincentngthu commented on homework5.js
> +	const result = await requestPromise(`http://localhost:3000/${i}`).then().catch((e) => { sendMsg(e) })
await就不用then了

2018-05-25 09:45 UTC, vincentngthu commented on homework5.js
> +palyPromise()
这三个函数的返回值要是最后数字的结果

2018-05-25 09:45 UTC, vincentngthu commented on index.js
> +	const randomNumF = Math.random() * 10000
最大值1000000

2018-05-28 03:14 UTC, vincent-ng requested changes
注意代码格式

2018-05-28 03:14 UTC, vincentngthu commented on homework5.js
> +			if (body === 'equal') { console.log(i); cb(i) } else if (body === 'bigger') {
这个格式eslint不报错吗

2018-05-28 03:14 UTC, vincentngthu commented on homework5.js
>  				if (remainder > 0) j = Number(j.toFixed(0)) + 1
向下取整的话，应该用Math.floor

2018-05-28 03:14 UTC, vincentngthu commented on homework5.js
>  let minNumber = 0
这两个变量做成局部的吧

2018-05-28 03:14 UTC, vincentngthu commented on homework5.js
> +async function guessPromise(i) {
promise的实现方式，不能出现async和await关键字。否则跟async/await实现方式没什么区别了。

2018-05-28 03:16 UTC, xiaoqiang0723 commented on homework5.js
> +			if (body === 'equal') { console.log(i); cb(i) } else if (body === 'bigger') {
不报错。

2018-05-28 08:17 UTC, vincent-ng requested changes

2018-05-28 08:17 UTC, vincentngthu commented on homework5.js
> +				if (remainder > 0) j = Math.floor(j) + 1
貌似这三句可以直接写成j = Math.floor((min + max) / 2)
其他地方同理

2018-05-28 08:17 UTC, vincentngthu commented on homework5.js
> +function callback(i, maxNumber, minNumber, cb) {
这个i其实可以去掉的，min，max，cb即可
函数执行时首先猜的是min和max的中位数，向下取整。

2018-05-28 08:17 UTC, vincentngthu commented on homework5.js
> +function guessPromise(i, maxNumber, minNumber, cb) {
promise方式实现，不能出现callback

2018-05-28 08:17 UTC, vincentngthu commented on homework5.js
> +console.log('guessNumber by async', guessNumber)
async方法返回值是promise，所以可以调用then的

2018-05-28 08:47 UTC, vincent-ng requested changes

2018-05-28 08:47 UTC, vincentngthu commented on homework5.js
>  				const maxNum = i
这变量也可以不用声明了

2018-05-28 08:47 UTC, vincentngthu commented on homework5.js
> +			return guessPromise(maxNum, minNumber)
这样调用，最后的结果就无法返回给外面了

2018-05-28 08:47 UTC, vincentngthu commented on homework5.js
>  play((guessNumber) => {
callback的参数，第一个是err，第二个是返回值。
err不要在函数内部吃掉，有错的时候要让外部知道

2018-05-28 08:50 UTC, vincentngthu commented on homework5.js
> +		console.log(i)
函数内部，不要console.log
在函数调用者那里console.log

2018-05-28 09:29 UTC, vincent-ng requested changes
优化一下错误处理

2018-05-28 09:29 UTC, vincentngthu commented on homework5.js
> +function sendMsg(error) {
去掉这个函数

2018-05-28 09:29 UTC, vincentngthu commented on homework5.js
> +	}).catch((e) => { sendMsg(e) })
error往上抛就行，不要函数内部吃掉

2018-05-28 09:29 UTC, vincentngthu commented on homework5.js
> +})
async和promise函数不要带callback

2018-05-28 09:44 UTC, vincent-ng requested changes

2018-05-28 09:44 UTC, vincentngthu commented on homework5.js
> +		if (response.statusCode !== 200) {
这里要用if else，不然会调用了2次cb

2018-05-28 09:44 UTC, vincentngthu commented on homework5.js
> +	let number = 0
这个变量删掉吧，代码会简洁点
下同

2018-05-28 09:44 UTC, vincentngthu commented on index.js
> +	client.set(cacheKey + formtype, `${randomNum}`, callback)
其实可以调用三次start，开始三次游戏的。。

2018-05-28 10:10 UTC, vincent-ng requested changes
差不多了，没用的注释可以删掉

2018-05-28 10:10 UTC, vincentngthu commented on homework5.js
> +	const result = await start().catch((err) => { console.log(console.log('err', err)) })
async await的话，一般是用try catch来捕获异常的，不过这样写也可以

2018-05-28 10:10 UTC, vincentngthu commented on homework5.js
> +		guessAsync(maxNumber, minNumber).then((res) => {
async function还是用await调用吧

2018-05-29 00:32 UTC, vincent-ng requested changes

2018-05-29 00:32 UTC, vincentngthu commented on index.js
> +		const set = responContent === 'equal' ? () => { } : () => {}
改成三个代码串行执行吧，程序四的代码尽量不改

2018-05-29 01:57 UTC, vincent-ng approved these changes
把没用的注释清理一下

2018-05-29 02:10 UTC, merged